name: 'W-Extend'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '55 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    #runs-on: macos-12

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          
#         - name: 'Update Chrome & Driver'           
#           run: |
#             sudo apt-get remove google-chrome*
#             wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#             echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
#             sudo apt-get update 
#             sudo apt-get --only-upgrade -y install google-chrome-stable
#             cd /usr/local/share/chrome_driver
#             rm -f chrome_driver
#             cd /usr/bin
#             sudo wget -N https://chromedriver.storage.googleapis.com/105.0.5195.52/chromedriver_linux64.zip
#             sudo unzip -o chromedriver_linux64.zip
#             sudo chmod +x /usr/bin/chromedriver

            

        - name: 'Install requirements'
          run: |
            pip3 install -r ./requirements.txt
            pip3 install undetected-chromedriver
            pip3 uninstall -y selenium
            pip3 install selenium==4.2.0
            pip3 install --upgrade requests

            
        - name: 'Renew'
          env:
            USER_ID: ${{ secrets.USER_ID }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 ./main-w.py
